In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../../assets/Datasets/NYC_Greenhouse_Gas_Emissions_Inventory_20241206.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 87 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Inventory Type                        85 non-null     object
 1   Sectors Sector                        85 non-null     object
 2   Category Full                         85 non-null     object
 3   Category Label                        85 non-null     object
 4   Source Full                           85 non-null     object
 5   Source Label                          85 non-null     object
 6   Source Units                          85 non-null     object
 7   CY 2005 Consumed                      85 non-null     float64
 8   CY 2005 tCO2e (100 yr GWP)            85 non-null     float64
 9   CY 2005 Source MMBtu                  85 non-null     float64
 10  CY 2005 tCO2e (20 yr GWP)             85 non-null     float64
 11  CY 2006 Consumed                      85 non-null     float64
 12  CY 2006 tCO2e (100 yr GWP)            85 non-null     float64
 13  CY 2006 Source MMBtu                  85 non-null     float64
 14  CY 2006 tCO2e (20 yr GWP)             85 non-null     float64
 15  CY 2007 Consumed                      85 non-null     float64
 16  CY 2007 tCO2e (100 yr GWP)            85 non-null     float64
 17  CY 2007 Source MMBtu                  85 non-null     float64
 18  CY 2007 tCO2e (20 yr GWP)             85 non-null     float64
 19  CY 2008 Consumed                      85 non-null     float64
 20  CY 2008 tCO2e (100 yr GWP)            85 non-null     float64
 21  CY 2008 Source MMBtu                  85 non-null     float64
 22  CY 2008 tCO2e (20 yr GWP)             85 non-null     float64
 23  CY 2009 Consumed                      85 non-null     float64
 24  CY 2009 tCO2e (100 yr GWP)            85 non-null     float64
 25  CY 2009 Source MMBtu                  85 non-null     float64
 26  CY 2009 tCO2e (20 yr GWP)             85 non-null     float64
 27  CY 2010 Consumed                      85 non-null     float64
 28  CY 2010 tCO2e (100 yr GWP)            85 non-null     float64
 29  CY 2010 Source MMBtu                  85 non-null     float64
 30  CY 2010 tCO2e (20 yr GWP)             85 non-null     float64
 31  CY 2011 Consumed                      85 non-null     float64
 32  CY 2011 tCO2e (100 yr GWP)            85 non-null     float64
 33  CY 2011 Source MMBtu                  85 non-null     float64
 34  CY 2011 tCO2e (20 yr GWP)             85 non-null     float64
 35  CY 2012 Consumed                      85 non-null     float64
 36  CY 2012 tCO2e (100 yr GWP)            85 non-null     float64
 37  CY 2012 Source MMBtu                  85 non-null     float64
 38  CY 2012 tCO2e (20 yr GWP)             85 non-null     float64
 39  CY 2013 Consumed                      85 non-null     float64
 40  CY 2013 tCO2e (100 yr GWP)            85 non-null     float64
 41  CY 2013 Source MMBtu                  85 non-null     float64
 42  CY 2013 tCO2e (20 yr GWP)             85 non-null     float64
 43  CY 2014 Consumed                      85 non-null     float64
 44  CY 2014 tCO2e (100 yr GWP)            85 non-null     float64
 45  CY 2014 Source MMBtu                  85 non-null     float64
 46  CY 2014 tCO2e (20 yr GWP)             85 non-null     float64
 47  CY 2015 Consumed                      85 non-null     float64
 48  CY 2015 tCO2e (100 yr GWP)            85 non-null     float64
 49  CY 2015 Source MMBtu                  85 non-null     float64
 50  CY 2015 tCO2e (20 yr GWP)             85 non-null     float64
 51  CY 2016 Consumed                      85 non-null     float64
 52  CY 2016 tCO2e (100 yr GWP)            85 non-null     float64
 53  CY 2016 Source MMBtu                  85 non-null     float64
 54  CY 2016 tCO2e (20 yr GWP)             85 non-null     float64
 55  CY 2017 Consumed                      85 non-null     float64
 56  CY 2017 tCO2e (100 yr GWP)            85 non-null     float64
 57  CY 2017 Source MMBtu                  85 non-null     float64
 58  CY 2017 tCO2e (20 yr GWP)             85 non-null     float64
 59  CY 2018 Consumed                      85 non-null     float64
 60  CY 2018 tCO2e (100 yr GWP)            85 non-null     float64
 61  CY 2018 Source MMBtu                  85 non-null     float64
 62  CY 2018 tCO2e (20 yr GWP)             85 non-null     float64
 63  CY 2019 Consumed                      85 non-null     float64
 64  CY 2019 tCO2e (100 yr GWP)            85 non-null     float64
 65  CY 2019 Source MMBtu                  85 non-null     float64
 66  CY 2019 tCO2e (20 yr GWP)             85 non-null     float64
 67  CY 2020 Consumed                      85 non-null     float64
 68  CY 2020 tCO2e (100 yr GWP)            85 non-null     float64
 69  CY 2020 Source MMBtu                  85 non-null     float64
 70  CY 2020 tCO2e (20 yr GWP)             85 non-null     float64
 71  CY 2021 Consumed                      85 non-null     float64
 72  CY 2021 tCO2e (100 yr GWP)            85 non-null     float64
 73  CY 2021 Source MMBtu                  85 non-null     float64
 74  CY 2021 tCO2e (20 yr GWP)             85 non-null     float64
 75  CY 2022 Consumed                      85 non-null     float64
 76  CY 2022 tCO2e (100 yr GWP)            85 non-null     float64
 77  CY 2022 Source MMBtu                  85 non-null     float64
 78  CY 2022 tCO2e (20 yr GWP)             85 non-null     float64
 79  CY 2023 Consumed                      85 non-null     float64
 80  CY 2023 tCO2e (100 yr GWP)            85 non-null     float64
 81  CY 2023 Source MMBtu                  85 non-null     float64
 82  CY 2023 tCO2e (20 yr GWP)             85 non-null     float64
 83  2005 - 2022 % change Consumed         85 non-null     float64
 84  2005 - 2022 % change tCO2e            85 non-null     float64
 85  2005 - 2022 % change Source MMBtu     85 non-null     float64
 86  2005 - 2022 % change tCO2e 20 yr GWP  85 non-null     float64
dtypes: float64(80), object(7)
memory usage: 57.9+ KB

In [14]:
melted_df = pd.melt(df, id_vars=['Inventory Type', 'Sectors Sector', 'Category Full', 'Category Label', 'Source Full', 'Source Label', 'Source Units'], var_name='concept', value_name='value')
melted_df.info()
melted_df.head(100)
melted_df.to_csv('../../assets/Datasets/NYC_Greenhouse_Gas_Emissions_Inventory_20241206_melted.csv', index=False)

#set data types
melted_df['Inventory Type'] = melted_df['Inventory Type'].astype('string')
melted_df['Sectors Sector'] = melted_df['Sectors Sector'].astype('string')
melted_df['Category Full'] = melted_df['Category Full'].astype('string')
melted_df['Category Label'] = melted_df['Category Label'].astype('string')
melted_df['Source Full'] = melted_df['Source Full'].astype('string')
melted_df['Source Label'] = melted_df['Source Label'].astype('string')
melted_df['Source Units'] = melted_df['Source Units'].astype('string')
melted_df['concept'] = melted_df['concept'].astype('string')
melted_df['value'] = melted_df['value'].astype('float')

melted_df = melted_df[melted_df['Inventory Type'] != 'Total']
melted_df.info()
melted_df.head(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6800 entries, 0 to 6799
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Inventory Type  6800 non-null   object
 1   Sectors Sector  6800 non-null   object
 2   Category Full   6800 non-null   object
 3   Category Label  6800 non-null   object
 4   Source Full     6800 non-null   object
 5   Source Label    6800 non-null   object
 6   Source Units    6800 non-null   object
 7   concept         6800 non-null   object
 8   value           6800 non-null   float64
dtypes: float64(1), object(8)
memory usage: 478.3+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 6720 entries, 0 to 6798
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Inventory Type  6720 non-null   string
 1   Sectors Sector  6720 non-null   string
 2   Category Full   6720 non-null   string
 3   Category Label  6720 non-null   string
 4   Source Full     6720 non-null   string
 5   Source Label    6720 non-null   string
 6   Source Units    6720 non-null   string
 7   concept         6720 non-null   string
 8   value           6720 non-null   float64
dtypes: float64(1), string(8)
memory usage: 525.0 KB

,Inventory Type,Sectors Sector,Category Full,Category Label,Source Full,Source Label,Source Units,concept,value
0,GPC,Stationary Energy,Residential (small and large residential),Residential,#2 fuel oil,#2 fuel oil,gallon,CY 2005 Consumed,1.466460e+08
1,GPC,Stationary Energy,Residential (small and large residential),Residential,#4 fuel oil,#4 fuel oil,gallon,CY 2005 Consumed,7.786078e+07
2,GPC,Stationary Energy,Residential (small and large residential),Residential,#6 fuel oil,#6 fuel oil,gallon,CY 2005 Consumed,1.938461e+08
3,GPC,Stationary Energy,Residential (small and large residential),Residential,Biofuel,Biofuel,gallon,CY 2005 Consumed,7.194951e+05
4,GPC,Stationary Energy,Residential (small and large residential),Residential,Electricity,Electricity,kWh,CY 2005 Consumed,1.416836e+10
...,...,...,...,...,...,...,...,...,...
96,GPC,Stationary Energy,"Commercial and Institutional (commercial, inst...",Commercial and Institutional,#2 fuel oil,#2 fuel oil,gallon,CY 2005 tCO2e (100 yr GWP),8.597640e+05
97,GPC,Stationary Energy,"Commercial and Institutional (commercial, inst...",Commercial and Institutional,#4 fuel oil,#4 fuel oil,gallon,CY 2005 tCO2e (100 yr GWP),1.528176e+05
98,GPC,Stationary Energy,"Commercial and Institutional (commercial, inst...",Commercial and Institutional,#6 fuel oil,#6 fuel oil,gallon,CY 2005 tCO2e (100 yr GWP),2.689609e+05
99,GPC,Stationary Energy,"Commercial and Institutional (commercial, inst...",Commercial and Institutional,Biofuel,Biofuel,gallon,CY 2005 tCO2e (100 yr GWP),1.200000e+00
100,GPC,Stationary Energy,"Commercial and Institutional (commercial, inst...",Commercial and Institutional,Electricity,Electricity,kWh,CY 2005 tCO2e (100 yr GWP),1.307270e+07

In [19]:
#add column year from concept
melted_df['year'] = melted_df['concept'].str.extract(r'(\d{4})')

#remove values with 'change' or 'Change' in concept
melted_df = melted_df[~melted_df['concept'].str.contains('Change')]
melted_df = melted_df[~melted_df['concept'].str.contains('change')]




melted_df.to_csv('../../assets/Datasets/NYC_Greenhouse_Gas_Emissions_Inventory_20241206_melted_cleaned.csv', index=False)